# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bbs',
            options={},
        ),
        migrations.RenameField(
            model_name='bbs',
            old_name='author',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='bbs',
            old_name='pw',
            new_name='videoId',
        ),
        migrations.RemoveField(
            model_name='bbs',
            name='content',
        ),
        migrations.AddField(
            model_name='bbs',
            name='artist',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bbs',
            name='thumbnailUrl',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
